schema-version: v2
kind: plugin
metadata:
  name: go-starting
  display-name: go-starting
  description: Plugin to start a project with go
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - go
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  single-use: False
  repository: https://github.com/silastgoes/stackspot-go-starting-project.git
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - Api
  stk-projects-only: false
  inputs:
    - label: Project name
      type: text
      name: project_name
      default: project-name
      pattern: '([A-Z][a-z\-]+)+'
    - label: Description
      name: description
      type: text
      required: true