schema-version: v2
kind: plugin
metadata:
  name: docker-go-starter
  display-name: docker-go-starter
  description: Plugin para criar arquivos dockerfile de desenvolvimento e produção
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  single-use: False
  repository: https://github.com/silastgoes/stackspot-go-starting-project.git
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - Api
  stk-projects-only: false
  inputs:
    - label: Type name of your resource
      name: resource
      type: text
      required: true
      default: Client
      pattern: '([A-Z][a-z]+)+'
      help: 'Inform your resource name (e.g.: Client)'
    - label: Choose http method of new endpoint
      name: method
      type: text
      items:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      default: GET
      required: true
      help: 'Inform the method of the endpoint (e.g.: post or delete)'