schema-version: v2
kind: plugin
metadata:
  name: docker-go-starter
  display-name: docker-go-starter
  description: Plugin para criar arquivos dockerfile de desenvolvimento e produção
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  single-use: False
  repository: https://github.com/silastgoes/stackspot-go-starting-project.git
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - Api
  stk-projects-only: false
  inputs:
    - label: Project Name
      type: text
      name: project_name
      default: project-name
      pattern: '([A-Za-z\-]+)+'
    - label: Project Path
      type: text
      name: project_path
      default: project-path
    - label: Description
      name: go_version
      type: text
      default: 1.21.5
      pattern: '([0-9\.]+)+'
      required: true
    - label: Porject Port 
      name: project_port
      type: int 
      default: 5050